Merged release 2.0.9
Squashed commit of the following:

commit 60b42f20f222df9da07a01ee444327348b9f54ee
Author: Peter Hunt <pehunt@redhat.com>
Date:   Mon Jan 6 10:52:09 2020 -0500

    bump to version 2.0.9

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit 1560392d56352c7eccabb7219fcd6a2c5ab81774
Author: Mrunal Patel <mrunalp@gmail.com>
Date:   Sat Jan 4 13:04:58 2020 -0800

    Add TimedOutMessage to config to share with go code

    Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

commit b17d81bd7dbfc39ea85593e2a113c0c604d6eb1b
Author: Riccardo Schirone <sirmy15@gmail.com>
Date:   Fri Dec 20 17:38:42 2019 +0100

    Fixes format string to limit the size of the string to 10 characters

    %10s just ensures that when printing, at least 10 characters are
    written. However, in this case we probably want *at most* 10 characters
    to be written.

    Signed-off-by: Riccardo Schirone <sirmy15@gmail.com>

commit 3a11e260a4b81503199ae073dbce0bf9839049ce
Author: Riccardo Schirone <sirmy15@gmail.com>
Date:   Fri Dec 20 18:20:28 2019 +0100

    g_file_{get,set}_contents return a gboolean to indicate failure, use it

    Signed-off-by: Riccardo Schirone <sirmy15@gmail.com>

commit c2e2e6723ce522e6400cfeedc9fad212d0462d8c
Merge: fe2ebfd 0c66b66
Author: Daniel J Walsh <dwalsh@redhat.com>
Date:   Fri Dec 13 14:35:09 2019 -0500

    Merge pull request #105 from haircommander/bump-2.0.8

    Bump 2.0.8

commit 0c66b669a8a9569c5703300b52c8fb11ebf63925
Author: Peter Hunt <pehunt@redhat.com>
Date:   Fri Dec 13 14:22:13 2019 -0500

    bump to 2.0.9-dev

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit 5ca7df27cb3a6f1edaab1a40fcc61cc6c16d9308
Author: Peter Hunt <pehunt@redhat.com>
Date:   Fri Dec 13 14:22:00 2019 -0500

    bump to 2.0.8

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit fe2ebfd64892aac76f8953df712130290f1a650c
Merge: c8f7443 5bbd452
Author: Giuseppe Scrivano <gscrivan@redhat.com>
Date:   Fri Dec 13 20:20:44 2019 +0100

    Merge pull request #104 from haircommander/revert-oom

    Revert "conmon: check oom counter on cgroup v1"

commit 5bbd452f205e774a0e13b85c3ee19203495bb49a
Author: Peter Hunt <pehunt@redhat.com>
Date:   Fri Dec 13 12:09:27 2019 -0500

    Revert "conmon: check oom counter on cgroup v1"

    This reverts commit 4100fb20bc156fdd602f8684affa27e6b139d0ad.

    We found issues where the reading of the memory control file was racing with the cgroup manager's write. while we want to prevent false positives, not having false negatives is more important. Revert this commit until we find a more complete solution.

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit c8f7443640371822b4fa83c2df94733d650c4daf
Merge: 036ff29 7d8faa7
Author: Mrunal Patel <mrunal@me.com>
Date:   Thu Dec 12 15:13:27 2019 -0800

    Merge pull request #102 from haircommander/cgroup_v2_persist

    persist oom files on cgroup v2

commit 7d8faa73dc9b24d271be2834aa4009de3fd90d7e
Author: Peter Hunt <pehunt@redhat.com>
Date:   Thu Dec 12 11:04:52 2019 -0500

    persist oom files on cgroup v2

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit 036ff29786bbdd941403536b13320382e636a120
Author: Peter Hunt <pehunt@redhat.com>
Date:   Thu Dec 12 13:56:07 2019 -0500

    bump to v2.0.8-dev

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit d532caebc788fafdd2a305b68cd1983b4039bea4
Author: Peter Hunt <pehunt@redhat.com>
Date:   Thu Dec 12 13:55:53 2019 -0500

    bump to v2.0.7

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit faccd4016c963ff99f1239f645bd2a87813b1b52
Merge: 0760156 7d4c6be
Author: Mrunal Patel <mrunal@me.com>
Date:   Thu Dec 12 10:49:47 2019 -0800

    Merge pull request #100 from giuseppe/splice

    conmon: use splice(2) to copy from stdin

commit 07601566eb6ac13ce8003b7a62149ffacd04d349
Merge: 4100fb2 dc23660
Author: Mrunal Patel <mrunal@me.com>
Date:   Thu Dec 12 10:48:58 2019 -0800

    Merge pull request #101 from haircommander/bump-2.0.7

    Bump 2.0.7

commit dc236607c7dd393de8934f580c117e3d7136fed2
Author: Peter Hunt <pehunt@redhat.com>
Date:   Thu Dec 12 12:59:36 2019 -0500

    bump to version 2.0.8-dev

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit c35049c44303942da61560491caeba86e8d3fb67
Author: Peter Hunt <pehunt@redhat.com>
Date:   Thu Dec 12 12:59:18 2019 -0500

    bump to version 2.0.7

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit 7d4c6be9fe8b232c38ef0773e13aad5e13306528
Author: Giuseppe Scrivano <gscrivan@redhat.com>
Date:   Thu Dec 12 15:24:43 2019 +0100

    conmon: use splice(2) to copy from stdin

    the first advantage is that it is much faster as data is not copied
    from the kernel to the userspace and the back to the kernel, and the
    second advantage is that we don't block on writ'ing on the fd all the
    data we've buffered.

    Closes: https://github.com/containers/conmon/issues/99

    Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

commit 4100fb20bc156fdd602f8684affa27e6b139d0ad
Author: Giuseppe Scrivano <gscrivan@redhat.com>
Date:   Thu Dec 12 12:14:05 2019 +0100

    conmon: check oom counter on cgroup v1

    when running on cgroup v1, also check whether the OOM counter is > 0
    before writing the "oom" file.

    Previously, conmon was detecting an OOM every time an event fd was
    triggered.

    Unfortunately that is not enough, as an event on the eventfd is also
    triggered when the cgroup is deleted.  That could cause a race
    condition where conmon sees the event from the cgroup deletion before
    the SIGCHLD+SIGUSR1.  That could happen for example when systemd
    CollectMode is set for failed units.

    Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1782601

    Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

commit 95ed45ab361ede2dbd5e727d6e485f33f94b6f30
Merge: 8ba9575 82ef9c7
Author: Giuseppe Scrivano <gscrivan@redhat.com>
Date:   Thu Dec 12 12:21:59 2019 +0100

    Merge pull request #97 from mrunalp/persist_oom_file

    Persist the oom file when --persist-dir is specified

commit 82ef9c776ba543a9328d6a9dddc66dcc38be0af7
Author: Mrunal Patel <mrunalp@gmail.com>
Date:   Wed Dec 11 14:49:23 2019 -0800

    Persist the oom file when --persist-dir is specified

    Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

commit 8ba95756ee81607edc1d20704f6c86140493ece0
Author: Peter Hunt <pehunt@redhat.com>
Date:   Wed Dec 11 09:04:43 2019 -0500

    bump to v2.0.7-dev

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit 29c336700f2999acf9db07662b4a61355076e64a
Author: Peter Hunt <pehunt@redhat.com>
Date:   Wed Dec 11 09:04:25 2019 -0500

    bump to v2.0.6

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit ba14d9cc75d26d4e5db5d8b522dfc18b9bea90e5
Author: Giuseppe Scrivano <gscrivan@redhat.com>
Date:   Wed Dec 11 14:05:44 2019 +0100

    conmon: kill the process group on timeout

    when the timeout is expired, instead of killing the process, make sure
    to kill the entire process group.

    It is not safe as using pid cgroup or a pid namespace, which we cannot
    use as the script must run inside of the container pid namespace, but
    it addresses most common cases like bash forking a new process.

    Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1774184

    Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

commit bc9e976d7f198c8d840968ae51da67da70c397a6
Author: Peter Hunt <pehunt@redhat.com>
Date:   Tue Dec 10 12:48:56 2019 -0500

    bump to v2.0.6-dev

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit f91c1703d9a9aa734cbc3871e84c35d14499d305
Author: Peter Hunt <pehunt@redhat.com>
Date:   Tue Dec 10 12:48:39 2019 -0500

    bump to v2.0.5

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit c7925031cf675d6cda2d0d5059fb35d6c269e0f0
Author: Mrunal Patel <mrunalp@gmail.com>
Date:   Mon Dec 9 11:23:02 2019 -0800

    Write exit file to container bundle directory

    Write the exit file under the container bundle directory so
    it is available even when we restart the node. Also, keeping
    it scoped there makes the cleanup easier.

    Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

commit fd5ac47bc3d61456faee2e517da1c59371d7e7e8
Merge: df8c6aa c6835ed
Author: Daniel J Walsh <dwalsh@redhat.com>
Date:   Mon Dec 9 12:27:55 2019 -0500

    Merge pull request #91 from haircommander/version-2.0.4

    bump to version 2.0.4

commit c6835edaeb42a9b4536c2143ebb2a7708ea7b063
Author: Peter Hunt <pehunt@redhat.com>
Date:   Mon Dec 9 11:04:44 2019 -0500

    bump to version 2.0.5-dev

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit d930e38f50d1c062cedd5ac159293841622478b6
Author: Peter Hunt <pehunt@redhat.com>
Date:   Mon Dec 9 11:04:10 2019 -0500

    bump to version 2.0.4

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit df8c6aa516b22ca8fd28903024a90d9093d383e5
Author: Giuseppe Scrivano <gscrivan@redhat.com>
Date:   Mon Dec 2 16:41:03 2019 +0100

    conmon: fix tight loop on OOM

    inotify fails with EINVAL when trying to read an event with a too
    small buffer.

    Increase the size to "sizeof(struct inotify_event) + NAME_MAX + 1",
    that is enough to read at least one event.

    Closes: https://github.com/containers/conmon/issues/87

    Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

commit 42bce451a613f56ae9d6466ac89b3e41594fb93f
Merge: f6d23b5 5ae9942
Author: Daniel J Walsh <dwalsh@redhat.com>
Date:   Fri Nov 29 06:34:52 2019 -0500

    Merge pull request #89 from DaanDeMeyer/reduce-error-impact

    Initialize the endpoint for attach before calling fork.

commit 5ae994270b1490684b9a03f1b2fa47b15f61f6cb
Author: Daan De Meyer <daan.j.demeyer@gmail.com>
Date:   Wed Nov 27 21:24:16 2019 +0100

    Initialize the endpoint for attach before calling fork.

    This way, when an error occurs in the attach endpoint logic, conmon can
    exit immediately without having to clean up the child process.

commit f6d23b51a3c56cccd4e13b4eea361e98e1855802
Merge: 098fcce 951052b
Author: Daniel J Walsh <dwalsh@redhat.com>
Date:   Mon Nov 11 15:48:46 2019 -0500

    Merge pull request #83 from haircommander/bump-2.0.4

    Bump to 2.0.3

commit 951052b62fdfdf2dd61efa2ad03b5fdbfc93c3ba
Author: Peter Hunt <pehunt@redhat.com>
Date:   Mon Nov 11 10:16:39 2019 -0500

    version 2.0.4-dev

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit eb5fa88c26fde5ce1e3f8a1d2a8a9498b2d7dbe6
Author: Peter Hunt <pehunt@redhat.com>
Date:   Mon Nov 11 10:16:23 2019 -0500

    version 2.0.3

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit 098fcceaecb68c47034b3789e9d63f1c5283b6a3
Merge: 002da25 496e8e4
Author: Giuseppe Scrivano <gscrivan@redhat.com>
Date:   Mon Nov 11 16:09:42 2019 +0100

    Merge pull request #82 from haircommander/try_other_pipe

     Handle window resize events in a different fifo

commit 496e8e41e2b31dece6399e3bf89630c8a8dc63af
Author: Peter Hunt <pehunt@redhat.com>
Date:   Thu Nov 7 22:01:48 2019 -0500

    config: include the two ctrl events

    Rather than having a comment saying "this should stay in sync", let's define a variable and import it there, so we're guarenteed to stay in sync

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit 1ed4f0213cd68d7697585ff407533cf5dacd3bcf
Author: Peter Hunt <pehunt@redhat.com>
Date:   Tue Nov 5 15:25:00 2019 -0500

    Handle window resize events in a different fifo

    The terminal_ctrl_fd was being overloaded with events. CRI-O wants to reopen the log files at any time, and podman wants to not drop window resize events on exec.

    But we can have both.

    Introduce winsz_fd_*, a special fifo pair for window resize events. The terminal_ctrl passes window resize events to the write side, and the read side can process them (after masterfd_stdout is initialized, so we have somewhere to write to and we don't drop events).

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit 002da2522941fde456f5213c8a5a96c9836c2592
Merge: 19a1d5c 8d66f44
Author: Daniel J Walsh <dwalsh@redhat.com>
Date:   Tue Nov 5 09:13:28 2019 -0500

    Merge pull request #81 from giuseppe/opt-tag

    src: add new option --log-tag

commit 8d66f44c6237ba1184538efbd45f2156e83659bc
Author: Giuseppe Scrivano <gscrivan@redhat.com>
Date:   Tue Nov 5 09:59:07 2019 +0100

    src: add new option --log-tag

    it specifies an additional tag to use for logging messages.

    When using journald, it adds a tag "CONTAINER_TAG".

    Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

commit 19a1d5c48f5c05ec6fb72ec95411e51f25743460
Author: Sascha Grunert <sgrunert@suse.com>
Date:   Tue Oct 15 13:08:12 2019 +0200

    Add 'trace' log level support

    The trace log level is currently not supported by conmon, but seems to be
    a valid level for container runtimes like CRI-O and podman. This results
    that the container currently won't start if the log level is set to
    'trace'. Beside this, we now case insensitively compare the log level
    string to make it more fail safe.

    Signed-off-by: Sascha Grunert <sgrunert@suse.com>

commit bc758d8bd98a29ac3aa4f62a886575bfec0e39a1
Merge: e37aa48 cb4d0e3
Author: Giuseppe Scrivano <gscrivan@redhat.com>
Date:   Fri Oct 11 08:23:02 2019 +0200

    Merge pull request #77 from haircommander/v2.0.2-bump

    bump to 2.0.2

commit cb4d0e38210edfa945eeab783277cc8db9a8824d
Author: Peter Hunt <pehunt@redhat.com>
Date:   Thu Oct 10 08:42:17 2019 -0400

    version 2.0.3-dev

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit 65fe0226d85b69fc9e527e376795c9791199153d
Author: Peter Hunt <pehunt@redhat.com>
Date:   Thu Oct 10 08:41:45 2019 -0400

    version 2.0.2

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit e37aa48838b7d03cc7fcefcf86a3fd6035d2038b
Merge: 0e888a9 067c0a5
Author: Daniel J Walsh <dwalsh@redhat.com>
Date:   Thu Oct 10 06:42:21 2019 -0400

    Merge pull request #76 from giuseppe/fix-podman-hang

    conmon: close the sync pipe before exit command

commit 067c0a5ca47aa261e99521b32d6c74a8588b918c
Author: Giuseppe Scrivano <gscrivan@redhat.com>
Date:   Wed Oct 9 17:41:06 2019 +0200

    conmon: close the sync pipe before exit command

    before calling the exit command be sure the sync pipe is closed so
    that the waiting process can stop waiting.

    It solves an issue with Podman where the cleanup process could hang
    since the container is already locked by the podman process waiting
    on the sync pipe.  The reproducer here:

    podman --runtime /bin/false run --rm  alpine true

    Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

commit 0e888a95b9f7a632ce2557332967e142675cb661
Author: Sascha Grunert <sgrunert@suse.com>
Date:   Mon Oct 7 11:45:45 2019 +0200

    Add static binary build to Cirrus CI

    Signed-off-by: Sascha Grunert <sgrunert@suse.com>

commit 422ce21f1527f7624982748a36601401887aa181
Merge: 7286971 d7c90bd
Author: Daniel J Walsh <dwalsh@redhat.com>
Date:   Wed Sep 18 07:34:52 2019 -0400

    Merge pull request #74 from haircommander/conn_sock_config

    Add CONN_SOCK_BUF_SIZE to config

commit d7c90bdc5d17f8f55b17eef89f11e1fc31843425
Author: Peter Hunt <pehunt@redhat.com>
Date:   Tue Sep 17 15:04:35 2019 -0400

    Add CONN_SOCK_BUF_SIZE to config

    instead of having a note that says to sync the value

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit 72869713e1204b86ff19fff654e556858a81ecc6
Author: Valentin Rothberg <rothberg@redhat.com>
Date:   Fri Sep 13 16:20:48 2019 +0200

    bump to v2.0.2-dev

    Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

commit 4dc8bcfec41e10ca760c8e2089474c2843dfd066
Author: Valentin Rothberg <rothberg@redhat.com>
Date:   Fri Sep 13 16:20:28 2019 +0200

    v2.0.1

    * set masterfd_stdout before regsitering ctrl_cb
    * Add static & containerized targets to Makefile.
    * Makefile: don't fail if clean is called without a build
    * Fix compilation with clang
    * conmon: propagate error code from the container

    Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

commit 35437e482a0a5c08721e890023aa0bb6bf1e42a7
Merge: 4d36cb6 9e1e1ff
Author: Valentin Rothberg <rothberg@redhat.com>
Date:   Fri Sep 13 10:11:09 2019 +0200

    Merge pull request #71 from haircommander/stdout-wait-ctrl

    set masterfd_stdout before regsitering ctrl_cb

commit 9e1e1ffc5488ee8ff53057a855f1bd5343895695
Author: Peter Hunt <pehunt@redhat.com>
Date:   Thu Sep 12 15:59:20 2019 -0400

    set masterfd_stdout before regsitering ctrl_cb

    exec with conmon ran into issues because the manager attempted to resize the window before stdout was configured. Thus, we got the ctrl_cb from the caller, but had no where to send the ioctl.

    Fix this by registering the callback after we set stdout.

    Signed-off-by: Peter Hunt <pehunt@redhat.com>

commit 4d36cb6af54f6963c5bf2d449f36057a22783974
Merge: fac48d0 58ce137
Author: Daniel J Walsh <dwalsh@redhat.com>
Date:   Wed Sep 4 16:06:00 2019 -0400

    Merge pull request #69 from mgoltzsche/static-build

    Add static & dockerized targets to Makefile.

commit 58ce1379fff02730abee077e8c48f97c635ad0df
Author: Max Goltzsche <max.goltzsche@gmail.com>
Date:   Tue Sep 3 21:57:38 2019 +0200

    Add static & containerized targets to Makefile.

    Signed-off-by: Max Goltzsche <max.goltzsche@gmail.com>

commit fac48d034d625f5366a6526f94e362deaa14d18d
Merge: 8a56404 6ef63df
Author: Daniel J Walsh <dwalsh@redhat.com>
Date:   Sat Aug 31 06:25:52 2019 -0400

    Merge pull request #68 from agners/master

    Makefile: don't fail if clean is called without a build

commit 6ef63dfcc65d5401bc7cc7170d569cefcdadcb38
Author: Stefan Agner <stefan@agner.ch>
Date:   Fri Aug 30 17:49:22 2019 +0200

    Makefile: don't fail if clean is called without a build

    Do not fail when calling the clean target without building first.

    Signed-off-by: Stefan Agner <stefan@agner.ch>

commit 8a56404fa7759f4901cf989e60d31c1e04af53db
Merge: af8e5a6 6d4f502
Author: Giuseppe Scrivano <gscrivan@redhat.com>
Date:   Tue Aug 20 16:33:23 2019 +0200

    Merge pull request #66 from openSUSE/clang-fix

    Fix compilation with clang

commit 6d4f5022ac36e69e0cad9dd7fc4bddea8af9d77e
Author: Sascha Grunert <sgrunert@suse.com>
Date:   Tue Aug 20 15:27:38 2019 +0200

    Fix compilation with clang

    This fixes the missing field initializers error when compiling with
    clang:

    ```
    src/conmon.c:119:7: error: missing field 'short_name' initializer
            {NULL}};
                 ^
    ```

    Signed-off-by: Sascha Grunert <sgrunert@suse.com>

commit af8e5a6bc82868d4346210ffeb462768cc6a18a6
Merge: a1cdfff 74da3fb
Author: Daniel J Walsh <dwalsh@redhat.com>
Date:   Mon Aug 19 10:25:01 2019 -0400

    Merge pull request #65 from giuseppe/conmon-return-exit-code-container

    conmon: propagate error code from the container

commit 74da3fb06d4444aca4724bddc8e61729600a4d81
Author: Giuseppe Scrivano <gscrivan@redhat.com>
Date:   Mon Aug 19 13:34:13 2019 +0200

    conmon: propagate error code from the container

    at exit propagate the return code from the watched container.  This is
    useful when running in systemd so it can properly detect a failure and
    restart the container if necessary.

    Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

commit a1cdfff60be1eb457d2d0e4a631c39e454197c1c
Author: Peter Hunt <pehunt@redhat.com>
Date:   Fri Aug 9 09:50:56 2019 -0400

    v2.0.1-dev

    Signed-off-by: Peter Hunt <pehunt@redhat.com>